// <auto-generated />
using System;
using Bargeh.Topics.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bargeh.Topics.Api.Infrastructure.Migrations;

[DbContext(typeof(TopicsDbContext))]
[Migration("20240308081604_Init")]
partial class Init
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        #pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bargeh.Topics.Api.Infrastructure.Models.Topic", b =>
        {
            b.Property<Guid>("Id")
             .ValueGeneratedOnAdd()
             .HasColumnType("uuid");

            b.Property<Guid>("AuthorId")
             .HasColumnType("uuid");

            b.Property<string>("Body")
             .IsRequired()
             .HasMaxLength(4096)
             .HasColumnType("character varying(4096)");

            b.Property<long>("Dislikes")
             .HasColumnType("bigint");

            b.Property<Guid>("ForumId")
             .HasColumnType("uuid");

            b.Property<long>("Funnies")
             .HasColumnType("bigint");

            b.Property<long>("Insights")
             .HasColumnType("bigint");

            b.Property<long>("Likes")
             .HasColumnType("bigint");

            b.Property<long>("Loves")
             .HasColumnType("bigint");

            b.Property<string>("Title")
             .IsRequired()
             .HasMaxLength(64)
             .HasColumnType("character varying(64)");

            b.HasKey("Id");

            b.ToTable("Topics");
        });
        #pragma warning restore 612, 618
    }
}