// <auto-generated />
using System;
using Bargeh.Topics.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bargeh.Topics.Api.Infrastructure;

[DbContext(typeof(TopicsDbContext))]
partial class TopicsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        #pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bargeh.Topics.Api.Infrastructure.Models.Topic", b =>
        {
            b.Property<Guid>("Id")
             .ValueGeneratedOnAdd()
             .HasColumnType("uuid");

            b.Property<Guid>("ForumId")
             .HasColumnType("uuid");

            b.Property<string>("Permalink")
             .IsRequired()
             .HasMaxLength(64)
             .HasColumnType("character varying(64)");

            b.Property<string>("Title")
             .IsRequired()
             .HasMaxLength(64)
             .HasColumnType("character varying(64)");

            b.HasKey("Id");

            b.ToTable("Topics");
        });
        #pragma warning restore 612, 618
    }
}