// <auto-generated />
using System;
using Bargeh.Forums.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bargeh.Forums.Api.Infrastructure.Migrations;

[DbContext(typeof(ForumsDbContext))]
[Migration("20240307052108_AddForumMemberships")]
partial class AddForumMemberships
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        #pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bargeh.Forums.Api.Infrastructure.Models.Forum", b =>
        {
            b.Property<Guid>("Id")
             .ValueGeneratedOnAdd()
             .HasColumnType("uuid");

            b.Property<string>("Description")
             .IsRequired()
             .HasMaxLength(350)
             .HasColumnType("character varying(350)");

            b.Property<long>("Members")
             .HasColumnType("bigint");

            b.Property<string>("Name")
             .IsRequired()
             .HasMaxLength(32)
             .HasColumnType("character varying(32)");

            b.Property<Guid>("OwnerId")
             .HasColumnType("uuid");

            b.Property<string>("Permalink")
             .IsRequired()
             .HasMaxLength(32)
             .HasColumnType("character varying(32)");

            b.Property<long>("Supporters")
             .HasColumnType("bigint");

            b.HasKey("Id");

            b.ToTable("Forums");
        });

        modelBuilder.Entity("Bargeh.Forums.Api.Infrastructure.Models.ForumMembership", b =>
        {
            b.Property<Guid>("Id")
             .ValueGeneratedOnAdd()
             .HasColumnType("uuid");

            b.Property<Guid>("ForumId")
             .HasColumnType("uuid");

            b.Property<Guid>("UserId")
             .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ForumId");

            b.ToTable("ForumMemberships");
        });

        modelBuilder.Entity("Bargeh.Forums.Api.Infrastructure.Models.ForumMembership", b =>
        {
            b.HasOne("Bargeh.Forums.Api.Infrastructure.Models.Forum", "Forum")
             .WithMany()
             .HasForeignKey("ForumId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();

            b.Navigation("Forum");
        });
        #pragma warning restore 612, 618
    }
}